language: python
python:
- '2.7'
services:
- redis-server
addons:
  postgresql: '9.3'
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install --upgrade pip
- pip install -r pip-freeze.txt --upgrade
- pip install coveralls
- npm install
before_script:
- psql -U postgres -c "CREATE USER temba WITH PASSWORD 'temba';"
- psql -U postgres -c "ALTER ROLE temba WITH SUPERUSER;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis_topology;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION hstore;"
- psql -U temba postgres -c "CREATE DATABASE temba;"
- ln -s $TRAVIS_BUILD_DIR/temba/settings.py.dev $TRAVIS_BUILD_DIR/temba/settings.py
script:
- node_modules/karma/bin/karma start karma.conf.coffee --single-run --browsers PhantomJS
- coverage run --source="." manage.py test temba/api temba/assets temba/campaigns
  temba/channels temba/contacts temba/flows temba/ivr temba/locations temba/msgs temba/orgs
  temba/public temba/reports temba/schedules temba/triggers temba/utils temba/values
  --verbosity=2 --noinput
after_success:
- coverage report -m --include="temba/api/*,temba/assets/*,temba/campaigns/*,temba/channels/*,temba/contacts/*,temba/flows/*,temba/ivr/*,temba/locations/*,temba/msgs/*,temba/orgs/*,temba/public/*,temba/reports/*,temba/schedules/*,temba/triggers/*,temba/utils/*,temba/values/*"
  --omit="*/migrations/*,*/tests" -i
- coveralls
notifications:
  slack:
    secure: L4CTQdnVu4fSh4xFj4+n3ATBMyiNsCHFAVtV/2MnQvXO/nkVUJujEfe4+XMf2HOEInZ7K9ZeCbQiOtlrwux7B8/6MhYSWR4An40c0bjggv6CBCObDZ8xT2tUFuK63TL/O+OSglJsfH/tMM0cHVV7KDzoxEIp+0u7vjcDt0LRhNE=
